<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="DESKTOP-8DQ5F38" failures="1" tests="1" name="FirefoxTest(failed)" time="34.203" errors="0" timestamp="2023-09-28T15:03:41 IST">
  <testcase classname="TestPackage.ExecutionUsingTestNG" name="VerifyChekoutButtonFunctinality" time="0.378">
    <failure type="java.lang.AssertionError" message="did not expect [https://www.saucedemo.com/checkout-step-one.html] but found [https://www.saucedemo.com/checkout-step-one.html]">
      <![CDATA[java.lang.AssertionError: did not expect [https://www.saucedemo.com/checkout-step-one.html] but found [https://www.saucedemo.com/checkout-step-one.html]
at TestPackage.ExecutionUsingTestNG.VerifyChekoutButtonFunctinality(ExecutionUsingTestNG.java:97)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1623)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- VerifyChekoutButtonFunctinality -->
  <testcase classname="TestPackage.ExecutionUsingTestNG" name="VerifyContinueButtonFunctionality" time="0.0">
    <ignored/>
  </testcase> <!-- VerifyContinueButtonFunctionality -->
  <testcase classname="TestPackage.ExecutionUsingTestNG" name="VerifyRemoveButtonFunctionality" time="0.0">
    <ignored/>
  </testcase> <!-- VerifyRemoveButtonFunctionality -->
</testsuite> <!-- FirefoxTest(failed) -->
